#!/bin/bash
no='\033[0m'		# Color Reset
ok='\033[32;01m'    # Green Ok
err='\033[31;01m'	# Error red
warn='\033[1;33m'   # Yellow
blue='\033[1;34m'   # Blue
purp='\033[1;35m'   # Purple
cyan='\033[1;36m'   # Cyan
white='\033[1;37m'  # White
lang="ru"
if [ "$lang" == "ru" ]; then
    compath="lang/ru/level0.md"
fi
if [ "$lang" == "en" ]; then
    compath="lang/en/level0.md"
fi
disp0="$(grep display0 $compath | sed -r 's/.{,10}//')"
disp1="$(grep display1 $compath | sed -r 's/.{,10}//')"  
disp2="$(grep display2 $compath | sed -r 's/.{,10}//')"
disp3="$(grep display3 $compath | sed -r 's/.{,10}//')"
compare() {
    comment="$(grep "comment${count}" $compath | sed -r 's/.{,12}//')"
    command="$(grep "command${count}" $compath | sed -r 's/.{,12}//')"
    success="$(grep "success${count}" $compath | sed -r 's/.{,12}//')"
    failure="$(grep "failure${count}" $compath | sed -r 's/.{,12}//')"
    # echo "$command $success "
}
cycle() {
    compare
    read -p "$comment" input
    comm=$(echo "$input" | cut -d ' ' -f 1)
    echo -e "$purp$disp0$no $blue$input$no"
    if [ $comm == $command ]; then
        echo -e "$cyan$disp1$no $ok$command$no"
        count=$(( $count + 1 ))
        name=$($command)
        echo -e "$blue$disp2$no"
        echo -e "$warn$name$no"
        echo -e "$ok$success$no"
    else
        name=$($input)
        echo -e "$warn$name...$no $err$failure$no"
fi
}
# trap "echo ' Trapped Ctrl-C'" SIGINT
# trap 'echo "Enter key pressed!"' RETURN
count=100
while [ $count -le 104 ]
do
cycle
done
